BASE_URL = "https://www.saucedemo.com/v1/"
BROWSER = "chrome"
USERNAME="standard_user"
PASSWORD="secret_sauce"
LANDING_PAGE_URL = BASE_URL + "inventory.html"
CHECKOUT_PAGE_URL = BASE_URL + "cart.html"